### ISSUE TITLE
Put Farsandra properties in a config file

### ISSUE THREAD

**Issue by oscerd** [edwardcapriolo/farsandra#5]
I was watching at Farsandra main class code. There are a lot of static strings used. Do you mind to put all of this properties outside of the class? Maybe in a configuration file? I would like to work on this, because I think this is a very promising project.

Thank you,
Bye,
Andrea

**Comment by edwardcapriolo** [comment]
In farsandra we are manipulating text files in a variety of formats. This in is always a bit difficult because it is a naive way to configure a complicated piece of software (cassandra). Farsandra understands some of the configuration and the domain model but not all.

We should make it as easy as possible to spin up farsandra. Is your plan to move the constructor properties of farsandra into a configuration file? 

Magic strings are always bad and taking them out is always a good thing. Send a small pr of what you are planning and we can go forward with what you want to do.

**Comment by oscerd** [comment]
Ok. I'll work on this.

What I'm thinking is to create a config file and ConfigHolder class.. Then
use this class to form strings in farsandra code.. In this way if se need
to change we have to change only config file.
Il 16/gen/2015 17:57 "edwardcapriolo" <notifications@github.com> ha scritto:

**Comment by edwardcapriolo** [comment]
Merged. I will likely release to central in the next couple of days.

**Comment by edwardcapriolo** [comment]
Thank you for your submission.

**Comment by oscerd** [comment]
Thank you. I would like to continue helping on this project.
